### ISSUE TITLE
Provide information about sizes of allocated/deallocated blocks in allocator interface

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#1039]
While working on #1030 we discovered that wrapping of allocators with `Allocator_guard` is currently not exact (not to say broken). The guard reasons about the _consumed_ amount from the `size` parameter in `alloc()` and `free()` and the statistical overhead of the wrapped allocator. This does not really work out for the following reasons
- With C++11, `delete` is not provided the deallocation size and, therefore, only works with deallocators that don't need the size parameter. This implies that the allocator guard is passed an invalid size.
- Even with a valid size parameter, the statistical overhead is not exact and, hence, any reasoning in the guard may miss its goal.
  I propose to enhance `Allocator::alloc` and `Deallocator::free` to return the real _allocated_ resp. _deallocated_ amounts.

**Comment by alex-ab** [comment]
bab59f5bf266f1e8dbd790b394a8cb0546cd4482 commit addresses this issue - please check. Additionally, if ok, I would create another commit to remove overhead() everywhere (which may be squashed if wanted so)

**Comment by chelmuth** [comment]
IMO `overhead()` should be removed.

**Comment by alex-ab** [comment]
I adapted the commit to the comments

**Comment by skalk** [comment]
Sorry for the quite late discussion contribution. I already talked with chelmuth and alex-ab on friday from face-to-face about this.
I was thinking about the inadequateness of the Allocator_guard sometimes ago, and came to the conclusion that the natural place for limiting RAM quota would be a RAM session guard instead of an allocator guard. I've implemented exemplary this within the nic_bridge: https://github.com/genodelabs/genode/blob/master/repos/os/src/server/nic_bridge/component.h#L46
When having a Ram_guard in combination with a Heap (maybe even in general in the future) as part of a RPC object, one could easily do all allocations client-wise, having dedicated dataspaces (like a sliced heap) and correct quota-calculations, no need for changing any Allocator API nor implementation.
Another small advantage is that there are very few Allocator_guards actually used. So a corresponding replacement will not hurt too much. The only show-stopper right now is that the Heap's standard slab size (for its meta-data) and therefore its initial slab is quite big (8K) which increases the default session costs.

**Comment by skalk** [comment]
I forgot to mention: @chelmuth I completely agree with you regarding the removal of `overhead()`

**Comment by nfeske** [comment]
@skalk I like the idea but would prefer to discuss it separately from this issue and go with @alex-ab's change for now.

* Alex' change of the `Allocator` is good regardless of the `Allocator_guard`. Sure, it was motivated by the problem of the guard but reflecting the allocation costs to the caller is certainly a sensible feature.
* In many component implementations, the session-component object already gets a metadata allocator as constructor argument. At this level, the developer does no longer need to care about RAM sessions, just allocators. In those implementations, the current `Allocator_guard` is a natural fit.
* I am hesitant to open another infrastructure-rework topic on top of the current one. Let us first get the current topic (async parent interface) out of the way. To do that, however, we need to solve the accounting problem. As Alex' suggestion is less intrusive than your's, I would go with Alex' patch for now.

That said, your idea makes perfect sense. In particular when looking at the platform driver where the guard is manually upgraded/downgraded to account for RAM allocations/transfers, your approach seems like a better fit. To go forward, I propose to move your new RAM guard to a public place (e.g., os/include/os/) so that we can use it in situations where the allocator-guard is typically used now. I don't mean to change all places at once but gradually. Maybe we notice that the RAM guard feels more natural, or not.

**Comment by alex-ab** [comment]
I updated the commits. Please review d28b04a0db33d2cc6c2be35565e4dcca96b4ed60 thoughtfully, I adapted (hopefully) all places where the allocator is used, especially base-*  code. a0400537c6dd163365ce04398b0ec141aa82b765 is not ready yet, since one place is left where [overhead()](https://github.com/alex-ab/genode/blob/issue_1039/repos/base/include/root/component.h#L130) is used - how to handle this case ?

**Comment by nfeske** [comment]
I would assume that a sliced heap is used for creating session-component objects. This is the case in all servers that care about the proper accounting of session-local resources. So we could so the following:

```
/* assume the use of a sliced heap, which consumes whole pages */
size_t const needed = page_rounded_size(sizeof(SESSION_TYPE));
```

In the future, I plan to retire the current version of `Root::Component` anyway. So it is ok to have an intermediate solution like this.

**Comment by alex-ab** [comment]
I followed the path as suggested by @skalk and used the Ram_session_guard as used by the nic_bridge. Please review the commits beginning with 'os: move ram_session_guard to util from nic_bridge' on the [branch](https://github.com/alex-ab/genode/commits/issue_1039_ram_guard). I would suggest to revert the ahci commit, as it nicely shows up the original issue (which is fixed with the commits now)

**Comment by nfeske** [comment]
Do we still need the `Quota_reservation` then?

**Comment by nfeske** [comment]
Apart from the two remarks, I like your change very much and would go for it.

**Comment by alex-ab** [comment]
Ok, i will move the guard header and will investigate whether I can skip Quota_reservation.

**Comment by alex-ab** [comment]
@nfeske: I moved the header. The `Quota_reservation` can't be skipped for now, mainly due to (your) change that the `env.ram()` session is used as reference to the device_pd Slave::Policy. Before your commit changes the ram session `_ram` of the `Platform_session` was used, which however should be only used for DMA memory allocations.

**Comment by nfeske** [comment]
Alright. Thanks for the investigation. In order to use the ram guard as ref-ram account for the device PD, we'd need to turn the `Ram_session_guard` into a real `Ram_session_component` in order to have a ram-session capability. I think that the current version is fine.

**Comment by nfeske** [comment]
@alex-ab I merged your commits to staging.

**Comment by nfeske** [comment]
The `Allocator_guard` is no more (https://genode.org/documentation/release-notes/20.05#Removed__Allocator_guard_). The quota accounting is now done at a much more suitable level of abstraction (`Ram_allocator` interface), which alleviates the problem raised by this issue.
