### ISSUE TITLE
Move file system helpers from fs_rom to os/include/file_system

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1564]
I'm opening this as a seperate issue because I have a few branches based on splitting these utilities.

**Comment by nfeske** [comment]
Thank you. I merged the patch to staging now. I hope you are fine with the abbreviated commit title. I shortened it to be compliant to git's 50-character convention.

**Comment by ehmry** [comment]
@chelmuth I've fixed the 'string_contains' namespacing issue in https://github.com/ehmry/genode/commit/5d56eb83ca467e5b4001b4b47d3feecd607aa6d6.

**Comment by chelmuth** [comment]
@ehmry thanks for dealing with the compilation issue that quickly. Unfortunately, I'd prefer to restrict the availability of `string_contains()` to the `File_system` namespace. The reason is that it's not needed by any `base` code and, therefore, does not belong into `base`. Would you mind to fix your fixup accordingly?

**Comment by ehmry** [comment]
Ok, string_contains in now in the File_system namespace, and I sqashed that back to the fs_rom commit.

**Comment by chelmuth** [comment]
Okay, I removed the old commit from staging, added 895ce50 and _force_ pushed. Please remember that it's easier for our work flow if you provide _fixup_ commits to your work-in-progress. Then we are able to gently push, which results in fast forwards to others merging their work into staging.

**Comment by ehmry** [comment]
Sorry about that, I should have payed better attention to the issue history.
