### ISSUE TITLE
Terminal: rich escape sequence support

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1643]
I've noticed that terminal from gems doesn't support the escape sequences produced by terminal_mux and libcurses. Should the terminal decoder be augmented to support more sequences, or should it be frozen for the sake of low complexity?

**Comment by nfeske** [comment]
This surprises me a bit because I regularly use ncurses with the terminal when running Vim in Noux. Are you sure that the TERM environment variable of the application is set to ```linux```?

Regarding your question, in the past, I used to extend the escape sequences as needed but tried to stay close to the linux terminal capabilities. Please do not hesitate to extend the decoder if the increase in complexity stays reasonable. As a very useful addition, I would like to see the support for function keys and mouse cursor/buttons added sometime.

**Comment by ehmry** [comment]
I'm not going to be working on this anytime soon, so I'm closing the issue.
