### ISSUE TITLE
codezero: remove unsupported old kernel

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1668]
The development of the codezero kernel seems to be dead. Moreover the only platform supported is rather old. We currently have no ability to nightly test things on top of the kernel. We can only guarantee that things are compiling for the kernel, but nobody uses it at all. On the other side, every deeper change of core and other kernel dependent code leads to costs when having a lot of kernels/platforms. Therefore, I'd like to remove the codezero kernel support from Genode.

**Comment by m-stein** [comment]
:+1:

**Comment by cnuke** [comment]
:+1:

**Comment by nfeske** [comment]
sniff... :-/ It seems like I am defeated. I can't help but have to agree with Stefan.

**Comment by chelmuth** [comment]
Merged into staging - builder will be disabled in a second.

**Comment by jayrulez** [comment]
Might Fiasco(not OC) and Pistachio be on the chopping block soon too?

**Comment by nfeske** [comment]
Sooner or later, we will eventually remove them since they are essentially dead projects. If one of them should cause big trouble, e.g., when updating our tool chain, we probably won't invest much time to keep them supported.

But in contrast to Codezero, those kernels are still covered by our automated tests and we use them sporadically for debugging purposes. E.g., L4/Fiasco was very useful during our recent investigations with non-write-combined video memory, MTRRs, and the page-attribute table (PAT). Also, I tend to be a bit sentimental about the original L4 kernels. So keeping them around is nice and fuzzy. ;-)
