### ISSUE TITLE
foc_odroid_x2: Gpio Support.

### ISSUE THREAD

**Issue by alexygallar2** [genodelabs/genode#1669]
Gpio support for odroid_x2

**Comment by alexygallar2** [comment]
This is the implementation for the basic configuration of GPIO pins for ODROID-x2. The interrupt handling is not implemented yet.

**Comment by chelmuth** [comment]
@skalk same as with #1678. This contribution calls the platform _exynos4_ while #1678 calls it odroid_x2. Maybe that is okay but I want to double-check.

**Comment by skalk** [comment]
@chelmuth : the same as with  #1678, the fixup commit is 19ff6bef01e7c53e0bfcba4f2b0f4e0869188a3a

@alexygallar2 : Thank you for your contribution! I've rebased your commit to current staging. Just a hint for future contributions: please have a look at our coding style (http://genode.org/documentation/developer-resources/coding_style), otherwise we've a lot of refactoring work to do on our side ;-).

**Comment by chelmuth** [comment]
@alexygallar2 I merged 8d74e3f, 88bbc4b, and 1dabe56 into staging. Please review for rebase issues.

**Comment by alexygallar2** [comment]
The gpio works well in ODROID-x2
