### ISSUE TITLE
Unlink recursion

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1750]
It is not clear at the VFS or File_system interfaces if unlink will recurse or fail on non-empty directories. I believe this is causing problems with libc and noux because under no conditions do either set errno to ENOTEMPTY.

POSIX does not do this, which I assume is keep operations in the kernel simple. An argument for recursive unlink would be that directory structures can be updated atomically at the block device, if there are VFS plugins that do that natively (I'm thinging of something like Venti).

I don't have a preference between the two for now, but we could always have it both ways with a recursive argument flag.

**Comment by nfeske** [comment]
Is there actually a need to define the behavior? How about the following approach:

* We introduce an error for the not-empty case. So any file system that cannot deal with recursive unlink is able to reflect the problem to the caller.
* File systems that are able to perform unlink recursively just do so. They will just never return the error. This allows sophisticated file systems to sweep deep file hierarchies at once. Otherwise, the client would need to repeatedly unlink each file individually, which does not scale well.
* If the file-system user wants to make sure that a directory is empty because unlinking it, if can just look inside prior issuing the unlink operation.

**Comment by ehmry** [comment]
Ok, I like this approach, I will add an error tomorrow.

**Comment by ehmry** [comment]
I'm rebasing against master on the branch issue1750, the ram plugin is not recursive, but that can be fixed at the same time as #1780.
