### ISSUE TITLE
hw: lazy FPU context switch leads to in-kernel pagefault

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#1855]
Lazy FPU context switch on x86 and arm does not encounter that threads might get destroyed that are currently scheduled on the FPU. This leads to a page-fault or data-corruption when the FPU context of the already destroyed thread gets saved, because of a FPU context switch.

**Comment by m-stein** [comment]
Oh, nice that you have found this obvious bug. Blame on me that I didn't implemented this right for ARM in the first place.

**Comment by skalk** [comment]
To be honest, it was not that obvious when just analyzing the symptoms, and took quite some time to find the root cause for faulty, nested  (noux) bash processes on hw_x86_64.
This took me to the point, where I was thinking about hw and SMP, and I'm almost sure, we have the same problem there when destroying a thread that is currently executed on another CPU :-(

**Comment by m-stein** [comment]
After pressing "Comment", I realized that the term obvious was misleading and removed it ^^ I meant obvious from the perspective of the initial implementer.

**Comment by m-stein** [comment]
Some suggestions:
* In the commit message do you mean "implementation of the CPU and FPU context" instead of "implementation of the FPU and FPU context"?
* In the commit message, as far as I know, it is "an FPU" and not "a FPU" because the first spoken and not the first written letter is decisive.
* Personally, I would tend to separate the clean-up changes and the changes that fix the problem with the thread deletion in two different commits.
* May we also try to fix the FIXME's in arm/vfp.h in the context of this issue (extra commit)?

**Comment by skalk** [comment]
@m-stein: According to the first item: No, I meant it like it is stated.
Regarding the commit message and the usage of 'an': ok, @chelmuth would you correct this when finally merging the fixup commits?
The "FIXME"s as well as enabling the FPU for other ARM SoCs will be topic of another issue.
I've written a fixup commit that incorporates your other inline comments e06ca179fab2a3e17a52f70dd538b58985b3cd53.
I would like to circumvent the supplementary split of the commit into fixing the lazy switch and separating the FPU stuff. IMO the patch size is manageable, on the other hand its additional work I would like to avoid and I'm not sure who will profit from it.

**Comment by chelmuth** [comment]
Moved the commits to top of staging and squashed them already, please check.

**Comment by m-stein** [comment]
Looks good to me.
