### ISSUE TITLE
os: abandon Irq_activation and Irq_handler deprecated

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#2072]
Since the resolution of issue #1456, which turned the IRQ session interface into an asynchronous interface, there is no need for additional threads that wait for interrupts. Therefore, the helper classes `Irq_activation` and `Irq_handler` aren't necessary anymore. A simple `Signal_handler` should be enough. I would vote for marking the corresponding file `os/irq_activation.h` as being deprecated.

**Comment by nfeske** [comment]
Very good suggestion!

**Comment by skalk** [comment]
@nfeske above commit series solves the issue

**Comment by nfeske** [comment]
Since the header produces a compile error if included, we may better remove all other content. The `#error` makes the code unusable anyway.

Furthermore, I noticed that `grep -ri  "Irq_activation" repos` still yields a few results. They should be adapted before we merge the patch:

* os/src/drivers/nic/spec/lan9118/lan9118.h
* os/src/drivers/nic/gem/cadence_gem.h
* os/src/drivers/sd_card/spec/pl180/pl180.h

**Comment by skalk** [comment]
@nfeske I think you missed the other commits that reference the issue. They adapt the corresponding components.

**Comment by skalk** [comment]
@nfeske: fixup 5a50d92377f78299b3f03351d170622880776d37 removes the content from the header as desired ;-)
