### ISSUE TITLE
Grub2 config

### ISSUE THREAD

**Issue by jklmnn** [genodelabs/genode#2355]
Are there plans to add a Grub2 config to genode? And what would be the preferred way to do this?

**Comment by chelmuth** [comment]
We have no definite plans to support Grub2. But, there was a [discussion](https://sourceforge.net/p/genode/mailman/message/32994831/) on our mailing list two years ago, which revealed two possible solutions: Grub's `legacy_configfile` command and a script-file generator by Christian Menard. I have a personal preference for `legacy_file` because it can just chain-load the already generated config file. On the other hand, with @skalk developments on Genode single-file images (#2095) all boot configurations look alike as long as the kernel is not changed.

IIRC @alex-ab also has some up-to-date experiences with Grub2 during his work on #2242.

**Comment by jklmnn** [comment]
I tried the `legacy_configfile` but Grub2 got stuck after that command without any further output.

**Comment by alex-ab** [comment]
If you running on a machine with UEFI (no CSM resp. no BIOS legacy boot enabled), you won't get any output (#2242 addresses actual this issue). If you on a machine with CSM (Compatibility Support Module) enabled, you could see your expected scenario, if all went fine. If not, you would need to get somehow the serial output of the machine to get an idea of what went wrong.

**Comment by jklmnn** [comment]
Ah ok. Since my device supports neither BIOS nor CSM (UEFI only), the latter solution won't work for me. I'm going to try your modified bender.

Nevertheless I think it would be reasonable to add a native Grub2 for the future.

**Comment by ehmry** [comment]
I use syslinux with the mboot module, and syslinux should support UEFI.

**Comment by jklmnn** [comment]
I tried to boot it with the changed nova from @alex-ab and it worked.
