### ISSUE TITLE
init: attempt to replenish more quota than withdrawn

### ISSUE THREAD

**Issue by BorisMulder-CSL** [genodelabs/genode#2468]
For some components, when I start them up and stop them by changing init's config, core gives me the following error:

Warning: detach: no attachment at 0x180000
Error: attempt to replenish more quota than withdrawn

More strangely, when I see init's init_ram report, it will show a ram quota value that is increasing every time such a child exits. As if its ram quota is growing because the child has given him more quota back than the child should have access to. After a certain amount of starts and stops init even completely hangs.

I have experienced this issue when the child is virtualbox, and with fetchurl. For the latter, I have made a run script below that should reproduce this issue. It should be ready to run, except that for it to work the IP adresses in fetchurl and in nic_bridge should be changed to addresses inside your local network.

Can you reproduce this issue and perhaps make a fix?
[init_fetchurl.run.txt](https://github.com/genodelabs/genode/files/1187758/init_fetchurl.run.txt)

**Comment by nfeske** [comment]
Thank you for the detailed bug report and the test case! Just to double check, have you the commits f278024e44411509913ca3af9337bd6e53a1b9a5 and f95bfddc09113a83d8b1f1c2faecaa41d957079f present on your branch? They were added to master after 17.05 and address a problem that sounds very similar to what you are describing.

**Comment by BorisMulder-CSL** [comment]
Well, when I cherry pick those commits, core still gives this error.
However, the init report says init does not keep growing its RAM quota; instead the number remains constant. Init also still hangs after a while (though that might be a problem of my scenario).

**Comment by nfeske** [comment]
Please do not let the message irritate you too much. I left it there for myself but it appears in legit situations as well.

But the init-hanging problem is irritating. The only situation where a hang can legitimately happen is when env sessions are routed to child services that are misbehaving. E.g., when routing the env ROM session for the binary or dynamic linker to an fs_rom instance, init has to interact with fs_rom to load the ELF binary. Should the fs_rom service hang or become unavailable, init hangs as well. Init should not hang under any other circumstances.

**Comment by BorisMulder-CSL** [comment]
Just a question here: does every ROM session count as an environment session? So also the one for the config or some other rom module?
In my case it's the config that breaks it up. Init gets the config from a ram_fs, then some other component changes the file, and due to some race condition in maybe fs_rom things go wrong. I'm investigating this further.

**Comment by nfeske** [comment]
With the so-called "env" sessions, I refer to the sessions immediately created and called by the parent at the child construction. Specifically, these are the `Env_connection` objects found in `base/child.h`. They include the ROM for the executable and the dynamic linker as well as the child's PD and CPU sessions. Technically, the child's LOG session is also an env session. But as this session is newer called by the parent, it cannot pose any hanging of the parent (init).

The child's config ROM is not an env session because it is initiated by the child.

I recently encountered an issue related to the dynamic use of ram_fs and fs_rom (while I tried to emulate report_rom with fs_report, fs_rom, and ram_fs). Sometimes, file changes at the ram_fs remained unnoticed at the fs_rom client. Can you please check if the following commits make a difference? 

* c1ea08e511a612ee136d8476846d0153792b5236
* 2cffc0e30784d677c44cf822aa14200b37a2d8f0
* 59378fac535c5ab72aa29356e8ad0e2831923818

The corner cases are now covered by a new test (5c24516abf80729187266e112f579ac6669813fd). Right now, the commits cited above are at our staging branch.

**Comment by BorisMulder-CSL** [comment]
I tried cherry-picking those commits, but the fs_rom gives compiler errors now. Could it be that more commits are required that change something to fs_rom?

**Comment by nfeske** [comment]
Yes, the preceding commit 4e4071766bb0565e2180b3ee46c21644a5c50f3f looks important (also, there are no other commits between master and the ones I cited).

**Comment by BorisMulder-CSL** [comment]
With these new commits in 17.08, init's ram usage does not leak anymore. The warning and the error remain. If you think this is not a problem, this issue can be closed.
