### ISSUE TITLE
Concurrent signal and I/O handing for Nim

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2531]
Handling Genode signals with the Nim should follow the same conventions and idiom the of asynchronous I/O handling found in the standard library of the language, and should be processed concurrently with I/O operations. In order to do this the Nim calling context must suspend to block for signal processing in the same manner as it does for the libc ``select`` mechanism. The most sensible way I can think to do this is to expose the ``suspend`` and ``resume_all`` functions from the internal task API of libc to Nim's ``asyncdispatch`` module. Nim should suspend using ``select`` whenever possible and resort to ``suspend`` only when there are no file descriptors registered in the dispatcher. When the Nim the signal handling procedure is called from the kernel context during signal dispatching, that procedure must not execute application code but post an application callback to a queue, then call ``resume_all``.

I have a preview of the Nim side implemented at https://github.com/ehmry/Nim/commit/da776807dfbd513c58ce01df5fbc19c964d00c17, if the changes to the Genode API are approved, I would make a recipe to prepare and build my fork of Nim in the same manner as the GCC fork, and then submit a pull request to Nim upstream.

The changes to libc are simple, just a change to a header and the symbols at 789c2d5d6f9fc7c37dceb6de39fd930146ffab43.

This can be further streamlined but I have a simple example of signal handling here:
https://github.com/ehmry/genode-world/blob/287519c1ab174df6950d69615fc2089200b3fc6b/src/app/hotkey_edit/main.nim
(Start reading at the end).

**Comment by chelmuth** [comment]
I started a discussion with @ehmry in IRC and like to continue it here (mostly for time-zone reasons). A log of the current discussion follows.

<@chelmuth> I've to admit that I have "negative" feelings about mixing the base and C API even in Nim. Please don't get me wrong: I'm not rejecting pondering on your idea of integration. This feelings are just my starting point.
<@chelmuth> To explain myself more: The mix of base and C API directly leads to the point where we have to open up suspend()/resume_all(). The bad thing is that we're not certain that this is the best API which does not hurt if it's just internal. For example in case of resume_all(), we *deferred* the decision/investigation on directly resuming threads that where deblocked.
<@chelmuth> On the other hand, if we could avoid the mix then we could also stay with hiding those functions from users of the C runtime.
<@chelmuth> Another disadvantage with the current version of Libc::Kernel is the care that must be taken in signal handlers regarding *blocking* functions of the C runtime. This hurts most if the blocking function is an invisible transitive dependency of some Nim library.
<@chelmuth> That said I'd not completely dump the idea of hiding signal handling for users of the C runtime (which Nim is) behind select(). Do you see any chance in this direction?
<@ehmry> I see hiding signal handling behind select adding a lot of complication in cases like vsync on a framebuffer and monitoring and audio_out buffer
<@ehmry> one solution would seem to be to rewrite the Nim I/O to use the VFS directly instead of the libc, but that would break linking nim with C libraries that want to write to stdout
<@ehmry> 'App' signals could be used instead of 'Io' signals if the Nim application would return from construct rather than adhering to the 'main' convention
<@ehmry> a wait_and_dispatch_one_app_signal could fix this but I can understand that it should be avoided
<@ehmry> FWIW I think the libc task controlled would only be exposed for the benefit of other language runtimes

**Comment by ehmry** [comment]
A consideration that I may have forgone is handling RPC at the entrypoint, when the dispatch loop suspends into the libc kernel I doubt that will work as expected.

**Comment by ehmry** [comment]
This problem is solved by removing the explicit exit from the compiler. It follows that some sort of compile-time switch should be added that inserts an exit so that Nim programs written for POSIX can be compiled and will run as expected without manually modifying source code.

Fixed by https://github.com/nim-lang/Nim/pull/6515
