### ISSUE TITLE
wifi: update wpa supplicant

### ISSUE THREAD

**Issue by jklmnn** [genodelabs/genode#2541]
Due to the [recent security problems](https://www.krackattacks.com/) with WPA2, shouldn't the wpa supplicant in Genode use a newer release or fixed version?
According to `dde_linux/ports/dde_linux.port` wpa_supplicant 2.2 is in use.

**Comment by cnuke** [comment]
Thanks for the notice, we are well aware of the recent issue. Yes it must be updated. That being said, instead of applying a back-port patch from the git repository of the fix now, I opted for waiting until there is a proper upstream release and to update wpa_supplicant all together (after all the current version is quite old).

**Comment by cnuke** [comment]
Part of the update in 18.08.
