### ISSUE TITLE
trace_logger: convenient tracing frontend

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#2654]

**Comment by m-stein** [comment]
This is my suggestion for a basis of what could become a general tool for gathering, processing, and exporting tracing data in a convenient way.

083d3ba trace_logger: convenient tracing frontend
92d32a0 trace/policy/rpc_name: enable building again
b325527 AVL node/tree: make non-copyable
da4c23c trace_session: fix exception list in 'trace' RPC
ec82a31 base/trace/buffer.h: fix circular #include
437e692 create_uboot: better documentation
ff365e8 init config.xsd: add ld_verbose attribute

**Comment by m-stein** [comment]
Features I'd like to add in the future:
* Introduce domain tag similar to the NIC router configuration - So far, it is not possible to re-use one configuration for multiple policies.
* More systematic and descriptive names for configuration attributes
* Enable different output formats (log, report, FS ...) - I'm not sure with this one as there exists a variety of converter components that might do the job as well (then, the question would be which output format to use in the first place).
* Automatic test for the functionality of the trace_logger (current run-script is a mere demo)
* Gather more types of data (for instance RAM/CAP quota consumption)

**Comment by nfeske** [comment]
Thanks for this great commit series! I very much appreciate the great care that went into the trace_logger, in particular the clarity of the code, documentation, and the illustrative run script.

I merged the commits to staging.

Regarding your further ideas, I would wait with adding usability features before the tool has seen a good deal of use. I suggest to let's first see how far we get with the current version. Outputting the buffer to the LOG is fine as far as I can see. I support the idea to upgrade the run script to become an automated test. Regarding further events to capture, here are my ideas:

* Packet-stream operations (maybe capturing the number of packets that are in-flight to get an idea how well packets are batched?)
* The moment when a thread gets blocked on because of lock contention, and the moment when a thread gets unblocked when aquiring a contented lock.
* An easier way to insert manual instrumentations. Right now, manual trace entries can be generated by the `Thread::trace` function that takes a character pointer as argument, which is rather cumbersome. It would be cool to add trace-buffer entries with the same ease as we insert 'log' messages. E.g., how about adding a new `trace` function that works analogously to `log`, `warning`, `raw`, and `error`?

**Comment by m-stein** [comment]
@nfeske Your suggestions sound pretty cool to me, especially writing to the buffer with something alike Genode::log.

**Comment by m-stein** [comment]
@chelmuth In these commits the compile errors we had recently with b325527 should be fixed:
46cee2e trace_subject_reporter: fix missing include
65ae762 AVL node/tree: make non-copyable

**Comment by chelmuth** [comment]
What about the following targets?
```
- arndale: make LIB=core-hw
- arndale: make server/vmm
```

**Comment by m-stein** [comment]
@chelmuth I'm at it.

**Comment by m-stein** [comment]
@chelmuth Sorry for the inconvenience:
a890b94 trace_subject_reporter: fix missing include
2704697 AVL node/tree: make non-copyable
