### ISSUE TITLE
bash: rmdir dir/ (trailing slash) does not work

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2686]
When using bash's tab completion on a directory, the completed name has a trailing slash. However, rmdir stumbles over an directory argument with a trailing slash and refuses to delete the specified directory. It works after manually removing the trailing slash though.

As a possible solution, the libc could strip trailing slashes of the rmdir argument. Maybe, a similar issue exists for other file/path operations?

**Comment by NobodyIII** [comment]
This is probably related to "rm -r dir/" failing to delete the directory itself. I would love to see this fixed.

It sounds like our libc was designed for a less strict VFS implementation that allowed trailing slashes in paths. We probably need to remove trailing slashes from all libc file path strings in order to get the standard unix behavior.

**Comment by chelmuth** [comment]
It seems the libc could expect the kernel to strip the slash as `strace rmdir /tmp/delme/` shows on Linux.
```
rmdir("/tmp/delme/")                    = 0
```
So, we have to strip trailing slashes in *libc/file_operations.cc* `rmdir()`.

**Comment by nfeske** [comment]
Removed noux from the title. As far as I know, the problem still exists when using bash.

**Comment by nfeske** [comment]
Commit https://github.com/genodelabs/genode/commit/eb0a33302a0dfc0bf24a59a48a84f86bf390ab0d finally addresses this issue.
