### ISSUE TITLE
Pass root directory to VFS plugins

### ISSUE THREAD

**Issue by nfeske** [genodelabs/genode#2701]
In a growing number of VFS use cases, it is desirable to allow VFS plugins to use the VFS. This would ultimately allow the chaining of plugins.

**Comment by ehmry** [comment]
Perhaps the number of `Vfs::File_system` constructor arguments could be reduced with something like a `Vfs::Env` object with a `root_dir` accessor?

```
struct Vfs::Env
{
	virtual Genode::Env &env() = 0;
	virtual Genode::Allocator &alloc() = 0;
	virtual Vfs::Io_response_handler &io_handler() = 0;
	virtual File_system &root_dir() = 0;
	virtual Timeout_scheduler &timeout_scheduler() = 0;
};
```

What I really want is to sneak in the `timeout_scheduler`, which would increase the efficiency of timeouts in the VFS by using a single scheduler rather than creating multiple timer sessions. In the case of the libc VFS and a non-libc VFS, the timer connection would be lazily constructed.

**Comment by nfeske** [comment]
@ehmry introducing the `Vfs::Env` is a good idea. Let us do this as a subsequent step.

The remark about the timeout scheduler is interesting. I haven't had this problem so far but as more and more features will be implemented as VFS plugins in the future, I can see how this makes sense. That said, I find it important to not make the VFS inherently dependent on a timer session. So the `timeout_scheduler` must be constructed lazily - as done for timer session in the libc.

**Comment by nfeske** [comment]
Merged to staging.
