### ISSUE TITLE
nit_fb: add optional transparency

### ISSUE THREAD

**Issue by NobodyIII** [genodelabs/genode#2728]
Nitpicker supports transparency, and I propose that we extend that to nit_fb. I admit that there aren't very many obvious use cases for this, but it will help me debug my image renderer's transparency support.

I'm working on this myself, and I'll probably have a patch soon.

**Comment by NobodyIII** [comment]
I have this working with commit bedadbb in my nit_fb_transparency branch.

**Comment by nfeske** [comment]
That's a good suggestion. Thanks for posting the commit. This is certainly a good starting point. For the real integration, we should also consider that the alpha attribute might be toggled dynamically. Whenever this happens, the client should receive a mode-changed signal.

I'd prefer to call the attribute just 'alpha' because it is shorter. Also internally, we follow the convention to not prefix boolean members with `is_` or `has_` unless it sounds awkward otherwise. In this case, I'd call the member just `_alpha`.

**Comment by ehmry** [comment]
I'm drawn to this issue because I would like to request mode changes at the client-side and this could fit with requests for alpha. For my use case it would be sufficient to make synchronous and stateless requests and handle a mode change from my existing signal handlers. If the new mode comes with an alpha buffer, it seems to me that this would best be conveyed in the `Framebuffer::Mode` object when the client calls `Framebuffer::mode()`.

**Comment by nfeske** [comment]
@ehmry Would it be possible to request a mode change by re-constructing the `Framebuffer::Connection`? I would prefer this over extending the framebuffer session interface.

**Comment by nfeske** [comment]
BTW, I agree that adding the alpha attribute to `Framebuffer::Mode` makes much sense.

**Comment by ehmry** [comment]
@nfeske yes, that is probably sufficient, my only concern is speed, but I will have to test it before I make any complaints.

**Comment by chelmuth** [comment]
@NobodyIII are you still working on this feature? Did you already address @nfeske's remarks in https://github.com/genodelabs/genode/issues/2728#issuecomment-374874467?

**Comment by nfeske** [comment]
As nit_fb is going to become irrelevant in the light of https://github.com/genodelabs/genode/issues/3196. So I would not spend any energy on it.

**Comment by NobodyIII** [comment]
I don't remember the state of my code. I have too many other things that
I've been focusing on.

**Comment by nfeske** [comment]
@NobodyIII do you agree to close this issue?

**Comment by NobodyIII** [comment]
Yes.
