### ISSUE TITLE
fetchurl retry

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2733]
Fetchurl often fails to fetch for reasons that I care not to understand, but when run in a loop it will succeed. I don't want to add too many features to fetchurl, but a simple retry mechanism would make the tool much more robust.

**Comment by ehmry** [comment]
Patch at 3bff8f37af15193ec15cb25142564e488a0f0e29, @BorisMulder-CSL @nfeske do this fit your use-cases?

**Comment by BorisMulder-CSL** [comment]
So far I solved this case by having a management component respawn fetchurl in case it fails. Failing causes it to exit with a certain code because of CURLOPT_FAILONERROR, which is then reported by init such that the management code can take a certain action depending on the exit code, such as retrying or giving some message to the user. Moving the retry functionality to fetchurl would mean making fetchurl bigger, and my management component smaller. I do not really have a preference at the moment.

**Comment by ehmry** [comment]
I left the default as one attempt, no retry, so you shouldn't be affected if you don't set `<fetch retry="..."/>`.

**Comment by nfeske** [comment]
Merged to staging.
