### ISSUE TITLE
simplify fs_rom

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2833]
Fs_rom could be simpler.

**Comment by ehmry** [comment]
Patch at a0a716119f0cb0471881929bc38d1cd6d7106f8d.

**Comment by nfeske** [comment]
@ehmry closely related to this topic, I got new insights into the mysterious ID-space conflict when using fs_rom in the sculpt scenario. I can reproduce the problem now and found that fs_rom is not at fault. Instead, the problem is caused by the use of fs_rom (as child service) for the environment sessions other children. Apparently, init fails to wait for the response of close requests before issuing new session requests to fs_rom. I'm at it.

**Comment by ehmry** [comment]
@chelmuth I have two commits to fix the regression in `fs_rom`, 55717b7fb9d62bbd0d9c49cfaa07388e0f71e65f and d5fce652c574a311ee7d2a4dce5ec6dfd53f2d25. See my **fs_rom** branch.

The last patch to fs_rom was from older branch, and revert the component to a version without notification for empty files.

**Comment by chelmuth** [comment]
Thanks, the patches fix the run/fs_report issue. Unfortunately, the run/depot_query test is still broken (since ba91a2258803f24a0ba3f536071d4e08f59321ab). Could you please have a look?
