### ISSUE TITLE
trace: test-trace_logger fails on foc_pbxa9

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3080]
The condition the test has to achieve is never met on this platform. The "state" of the first thread always stays to be "UNTRACED" and never switches to "TRACED".

**Comment by skalk** [comment]
Is this a duplicate of issue #2809? @m-stein what went out of your investigation?

**Comment by m-stein** [comment]
This was the outcome, so far:
ad6dc57 base-linux: init trace control

But its not the same with the other platforms. I'm at it.

**Comment by nfeske** [comment]
@m-stein can you point me to the branch where ad6dc57179de332a813984d74bd6cb1929e08510 can be cherry-picked from?

**Comment by m-stein** [comment]
It's on staging:
af12ba6 base-linux: init trace control

**Comment by m-stein** [comment]
The problem apparently is the call of the ASM instruction in Trace::timestamp. The tracing itself works fine if I take out the timestamp in the test client. Otherwise the client gets stuck when calling the instruction without any hint in the log and never reaches the call of Thread::trace. It seems that Trace::timestamp never worked (I checked 18.08/05/02), but then I wonder why the timeout framework works.

**Comment by m-stein** [comment]
We can fix this by taking out the timestamp (it is not really needed for the test):
2f1959d test/trace_logger: don't use Trace::timestamp

**Comment by nfeske** [comment]
I added https://github.com/genodelabs/genode/commit/a1660268bbef6102ad00bd1da2f5fcdd056818a9 to staging.

**Comment by nfeske** [comment]
> I wonder why the timeout framework works.

Likewise.

**Comment by m-stein** [comment]
With the patch, test-trace_logger works also for okl4, sel4, fiasco and others that seemed to be broken beforehand on my machine.

The timeout test works for all these platforms but if I add a call to Trace::timestamp, it gets stuck at this call...

**Comment by chelmuth** [comment]
The test now succeeds.
