### ISSUE TITLE
ssh: add exec channel

### ISSUE THREAD

**Issue by sid-com** [genodelabs/genode#3401]

**Comment by m-stein** [comment]
:+1:

**Comment by m-stein** [comment]
Cool, that you sticked to this also after the hack'n'hike!
I just scrolled briefly through it - could it be that the file headers need an update? E.g. all headers in the ssh_terminal have the same description "Component providing a Terminal session via SSH" and all of them contain @cnuke as author. Or am I missing something?

**Comment by sid-com** [comment]
Thanks @m-stein !
Well, the large ssh_terminal/main.cc file is split up, because it made debugging easier. Most of it is code that @cnuke wrote... What is best practice in this case?

**Comment by cnuke** [comment]
Thanks for adding this feature, I appreciate that and will review it.

Normally one adds themself to the description header when “substantial” changes were made but we do not have guidelines for that AFAIK. That being said, I'm fine with how it is. However, providing only a single commit that includes the refactoring work as well as the newly added feature makes reviewing the changes more involved - from that perspective it would have been better to have sperate commits for that. When the changes enter the `master` branch they can be squashed anyway.

**Comment by sid-com** [comment]
I see your point. We came up with the same conclusion in our internal review. Let me know if there is anything I can do to make the review less cumbersome.

**Comment by cnuke** [comment]
Well, what's done is done - but please keep it in mind for future contributions.

**Comment by cnuke** [comment]
@sid-com I reviewed your commit. So far it looks good, both `ssh_terminal` run scripts still work. I rebased your commit to staging and applied a fix we did there to the component (see 7770b0d). 
Please see 4ed3cb7 for changes I made during the review - I mostly reverted cosmetic changes to the code as well as applied our coding style (alignment *space* vs. indentation *TAB*). That being said, it would be nice if you could extend the *README* with regard to the changed behaviour:

- There is now a `exit` report.
- Reports from concurrent logins will override each other and potentially lead to lost
  reports (this happens because there is now only one reporter for all logins - so far
  using multiple logins is not a common use0case so we can address this later but it
  should be documented).
- Detaching a terminal client will lead to a disconnect for the corresponding SSH sessions.
  Although have not used this "misfeature" of replacing a terminal client while keeping the
  session open, it should be documented nonethe less.

**Comment by sid-com** [comment]
@cnuke I added your suggestions to the README in commit 4c0e07d

**Comment by sid-com** [comment]
@chelmuth and @cnuke while testing we found that vim did not work properly. Fixed at eafd9e41510becce3b8f690d428a9cc3e5111560

**Comment by chelmuth** [comment]
I merged the series as 8019518dfea80e8dfbc06fcb3e62b6ca7d982793 just now.
