### ISSUE TITLE
Add shared component for making arm PSCI calls.

### ISSUE THREAD

**Issue by tworaz** [genodelabs/genode#3672]
It'd be nice to have a shared component that arm platforms can use in order to make PSCI calls.

**Comment by skalk** [comment]
Related to issue #3673

**Comment by skalk** [comment]
@tworaz now, I had the time to review your commit. Thank you for your nice work. Beside some very few  coding style  corners, I've changed the way how psci.h included psci_call.h, and moved the 32/64-bit call header into the src/include/hw path. The reason is that all headers in src/include/hw are independent from code in src/core or src/bootstrap, and this shouldn't be changed.
Please have a look at the resulting commit e9f58d9, and give me a sign, whether you like it or not.

**Comment by tworaz** [comment]
@skalk Thanks for taking the time to review and improve the code. The new version looks much better.

**Comment by nfeske** [comment]
Merged to staging.
