### ISSUE TITLE
Add support for Qemu arm virt machines to base-hw

### ISSUE THREAD

**Issue by tworaz** [genodelabs/genode#3673]
My long term goal is to add VirtIO driver framework and nic, input and framebuffer VirtIO drivers to Genode. The x86_64 qemu q35 machine can use VirtIO devices out of the box. The situation on arm is a bit more complex and VirtIO devices can only be exposed for custom "virt" machines. The goal here is to allow Genode using base-hw kernel to boot on such "virt" machines.

**Comment by tworaz** [comment]
For the record, this patch needs PSCI component from #3672 to work.

**Comment by skalk** [comment]
@tworaz thanks for providing both commits, it is pretty much welcome. I'll soon review your contribution.

**Comment by tworaz** [comment]
@skalk Please take your time, I'm not in a hurry. The VirtIO driver support for Genode which is my stated goal is more or less in a usable state already. The code needs some cleanup before I'll push it for review, however. The slightly outdate branch containing all my work so far can be seen here: https://github.com/tworaz/genode/commits/virtio.

**Comment by skalk** [comment]
@tworaz Ok, I reviewed this commit too. Beside the adaption needed to meet the minor change of the psci interface, I renamed arm_virt, as well as arm_64_virt to virt_qemu. The reason is that we already used that scheme for e.g. the zynq_qemu platform, and there are some virt_qemu solutions already flying around in some topic branches of some team members.
Thereby, I have put together the 32 and 64-bit versions as far as it is possible, and resigned to use different board names. Because the architecture reflects already the differences, but all peripherals can be the same in the future. The good thing about it is that we can spare some code duplications e.g. for the base-hw-virt_qemu package etc.
I hope you like the adaptions, which can be seen in commit 0fe6918. If you are ok with it, I would strive toward bringing it to staging. Thank you for your contribution!

**Comment by tworaz** [comment]
@skalk Thank you very much for taking your time to look at this.

The fun part is I did actually call this new platform qemu_virt at some point. AFAIR I switched to arm_virt and arm_64_virt after I've decided to support both ARMv8 and ARMv7 and while at it to also add RISC-V version. I think RISC-V board name ended up being rv64_virt. I still have that code stashed on a branch somewhere, but I'll probably won't have the time to get it into good enough shape for contributing to Genode. I basically lost interest in it after getting VirtIO nic driver working. Long story short qemu_virt does look fine to me. I'll need to make some adjustments to my work branch, but this is expected.

Please feel free to land your version on staging branch whenever you wish :)

**Comment by nfeske** [comment]
Merged to staging.
