### ISSUE TITLE
qt5: handle Genode signals as Qt signals in QPA plugin

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#3688]
Handling the Genode signals directly caused problems with multi-threaded applications (for example, page faults when resizing the Arora window) and can also lead to nested signal handler execution when blocking via `Libc::suspend()`, so it's still necessary to handle the Genode signals as Qt signals.

Related to #3644

**Comment by nfeske** [comment]
Thank you for the super quick investigation, @cproc!

**Comment by chelmuth** [comment]
For completeness: This solution just minimizes the mutex-contention window to the emission of queued `Q_SIGNALS` connections. A real fix had to move the nitpicker-signal handling (which has to be I/O level according to @cproc) behind the VFS border so that Libc synchronization, suspend, and also monitor will not end up in double suspend or unexpected nested execution of application/library code.
