### ISSUE TITLE
core-linux: make RAM quota configurable

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#3762]

**Comment by nfeske** [comment]
That looks good. But shouldn't we better name the environment variable `GENODE_RAM_QUOTA` instead of `CORE_RAM_QUOTA`? Since it must be defined in the Linux world, this name would make the meaning of this environment variable more obvious. Imagine seeing this environment variable defined in a .bashrc file.

**Comment by trimpim** [comment]
@nfeske I think, that renaming this variable to `GENODE_RAM_QUOTA` is a good idea, I'll update my branch.

**Comment by nfeske** [comment]
Thanks for the swift update. I merged your new commit to staging.

**Comment by chelmuth** [comment]
Merged to master
