### ISSUE TITLE
Sculpt: 'vbox5-nova-sculpt' menu cut off at bottom of screen when attempting to assign ROM (usb devices) resource

### ISSUE THREAD

**Issue by baconicsynergy** [genodelabs/genode#3771]
Attempting to assign ROM (usb devices) from the drop down menu for the vbox5-nova-sculpt component results in the bottom of the menu being cut off (sadly, the part that is needed).

Here is a picture of what happens: https://flic.kr/p/2j6mzNz

Changing the font does not fix the issue

Hope this helps! I wanted to file the issue before the next Sculpt release.

Using a Thinkpad x250

**Comment by nfeske** [comment]
I'm sorry for the late response. This topic was also discussed on the mailing list: https://lists.genode.org/pipermail/users/2020-April/007130.html

There are three ways to address this issue:

1. Reducing the complexity of options presented in the GUI - eliminating the need to scroll.
2. Allowing for the increase of resolutions when running Sculpt in a VM.
3. Adding scrolling support to the GUI.

We will have to address each of them sooner or later but I think that we should concentrate on the options (1) and (2) first because they undoubtely increase usability. In contrast, scrolling is prone to degrade usability if not implemented perfectly. So I'd not rush it.

That said, I cannot say for sure when to take concrete steps. I certainly won't consider it before wrapping up the current line of GUI-related work (https://genodians.org/nfeske/2020-06-23-gui-stack).
