### ISSUE TITLE
nova: add support to migrate global threads

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3842]

**Comment by alex-ab** [comment]
@nfeske, @chelmuth: please consider for review

**Comment by nfeske** [comment]
The changes look excellent! It is great to see also the collateral code improvements (like swapping out pointers for references). I have no reservation against merging the changes is as.

As one minor question, since the commit "base: add thread migration test" touches core, would it make sense to split it into two commits, one for the core-related changes, and one for the actual test?

**Comment by alex-ab** [comment]
@nfeske: thx, I rebased + adjusted the commits to your suggestions.

**Comment by alex-ab** [comment]
@nfeske: The factored out migration test into a standalone test is ready.

**Comment by nfeske** [comment]
@alex-ab Superb! I merged your commits to staging.
