### ISSUE TITLE
nova: support avx

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#3914]
As soon as it is supported by the kernel, also the vbox* and vm_session implemenation must be adjusted to store/restore the extended FPU state.

**Comment by nfeske** [comment]
What is the story behind this issue?

**Comment by alex-ab** [comment]
The idea is to enable [AVX](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) so that the load in guests can be reduced, e.g. for crypto, like AES, during video streaming of secured connections. Enabling this feature in the kernel is the one part, additional effort in our vm interface is required since other instructions must be used and the size of the FPU state increases.

**Comment by nfeske** [comment]
Thank you for the explanation. I'm admittedly not quite sure about the prioritization of this idea related to the many other topics at hand. Intuitively it feels a bit intangible to me, both regarding the effort needed and regarding the benefit.

Since you have opened this issue some months ago, how do you expect this issue to evolve?

**Comment by alex-ab** [comment]
> Since you have opened this issue some months ago, how do you expect this issue to evolve?

It is a side track which may or may not evolve, as time permit. We can close it for now.
