### ISSUE TITLE
cpu affinity: incorrect scaling to physical cpu number

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#4300]
Within Sculpt OS on top of the MNT Reform 2 (with 4 cpu cores) using the base-hw kernel I've adapted the sculpt_manager to use affinity (xpos=1, ypos=0, width=1,heigth=1) for the start nodes of menu-views and the file-browsers text-area. Unfortunately, this triggers an assertion in the base-hw kernel, because the generic code in the sandbox library and core scales this down to cpu-id "4", which is out of scope 0-3. The whole calculation is not base-hw specific.

**Comment by cnuke** [comment]
I stumpled upon the same issue with a faulty pkg *runtime* where I forgot to set the affinity levels in the sub-init but specified the affinity for a start node. Even if the proper fix lies elsewhere shouldn't we consider this commit as a band-aid solution for the time being?

**Comment by nfeske** [comment]
@cnuke the issue was rather mundane. Could you give https://github.com/nfeske/genode/commit/aadd5f61bf81f34291f99b0d5babce04cba18d8f at try?

The effect was an invalid init configuration, the affinity space of runtime being set to 1x1 but selecting the second CPU.

The assertion in base-hw should of course be replaced by proper sanitizing of the affinity arguments (e.g., wrapping the CPU coordinates at the affinity-space boundaries). Bad init configs can happen after all.

**Comment by cnuke** [comment]
@nfeske thanks for the commit. However, even with the fix applied, I still can trigger the assertion with the faulty sub-init configuration. I'll try to gather more detailed information.

**Comment by nfeske** [comment]
My patch does not fix the assertion. It only fixes the case where sculpt would trigger the assertion in the presence of @skalk's commit fc8c4d4ae9ec9641f94063b372a8bc80bdb0647a. The assertion need to be covered in core/base-hw.

**Comment by nfeske** [comment]
@cnuke https://github.com/nfeske/genode/commit/3b55a8b3a7e9e32d52a57eb5eb6d2224ba53a9b5 adds a diagnostic message to init/sandbox whenever an invalid affinity configuration is encountered. It also falls back to the default affinity location (the entire space) in this case. So it should circumvent the assertion. It does not replace the need for sanitizing the affinity in core or base-hw though.

**Comment by cnuke** [comment]
@nfeske thanks, I added the suggested check in 44455ee, which I came up with after instrumenting the session creation. I logged the affinity arguments and was a bit puzzled:

```
space: 4x1 affinity: (0x0/0+0+0x0)   # core
space: 4x1 affinity: (2x1/1+0+1x1)   # leitzentrale
space: 4x1 affinity: (8x1/8+0+8x1)   # my faulty runtime
```
`platform().affinity_space() ` comes first, followed by `affinity.space()` and `affinity.location()`. Naturally `0x0` is always a valid location and since the location pontentially narrows the space down I assume the check should be down against the underlying space.

**Comment by nfeske** [comment]
Thanks for your scrutiny @cnuke. I indeed mixed up the width/height with space.width/space.height.

Since the fiddling with coordinates is so brittle, I took a more profound attempt at improving the situation in https://github.com/nfeske/genode/commit/c3898b655688256a80306464f12f229ff53228dc. It works well in my test scenario. I'd appreciate you giving it try.

While revisiting the topic, I sense where some of the perceived fuzziness of the concept comes from. For some reason (ahem), the Genode API uses the `Affinity::Location` type as argument for the thread creation. In this case, however, only the x,y position is used. A distinct type would have been more appropriate. The two meanings of `Affinity::Location` in two different contexts is quite confusing.

**Comment by cnuke** [comment]
@nfeske commit c3898b6 is much appreciated and fixes the problem nicely, e.g. the warning points the user in the right direction.

Commit e87d8d7 fixes a minor compilation issue on base-hw (I have not checked other platforms).

**Comment by nfeske** [comment]
Thanks @cnuke for the nice feedback and the fixup. I rebased and merged the latest version to staging now.

**Comment by nfeske** [comment]
Fixed in master.
