### ISSUE TITLE
platform_drv: device is prematurely released if it was acquired multiple times

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#4379]
Yesterday, I incidentally constructed a use case in which the same device is acquired multiple times by the same component (in library code and in application code). The library subroutine, however, only temporarily creates the Platform::Device on the stack so that it is released when the subroutine returns. The application code intends to keep the Platform::Device and the corresponding Platform::Device::Mmio persistent. Now, when I run the library subroutine after the application code initialised the Platform::Device, the memory region attached by Platform::Device::Mmio becomes detached as a side effect.

I believe the culprit is in  [Session_component::release_device()](https://github.com/genodelabs/genode/blob/staging/repos/os/src/drivers/platform/session_component.cc#L183) resp. [Session_component::acquire_device()](https://github.com/genodelabs/genode/blob/staging/repos/os/src/drivers/platform/session_component.cc#L136). When the device component already exists on acquire, it's cap is returned. Yet, it is immediately released on `release_device()`, irrespective of how often the cap has been returned.

@skalk, I think either `acquire_device()` should fail instead of returning the same cap multiple times or we should apply some sort of reference counting to only release the device once the client releases the last instance of it. What do you think?

**Comment by skalk** [comment]
@jschlatow: I did not forbid the repeated aquisition of a device by the same session, because it seemed natural to me from an authorization perspective. Given your example of Platform::Device instances used on a stack, indeed this is a problem.
Given that we want to prevent others from doing so, I would vote for denial in this case, because when introducing reference counting I see additional complexity and new problems arising in the future.
Other opinions?
