### ISSUE TITLE
lx_emul: set task 'stack' member

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#4522]

**Comment by cnuke** [comment]
Commit [cc8072f](https://github.com/cnuke/genode/commit/cc8072fc392ddd480ec773115289d978a9a94545) sets the 'stack' member to the actual stack of the task rather than allocating member for the thread info.

**Comment by jschlatow** [comment]
@cnuke unfortunately, the commit is incompatible with arm (32bit) because it does not select `CONFIG_THREAD_INFO_IN_TASK` but actually expects a `struct thread_info` behind the `stack` member. In this configuration, we must therefore initialise the `stack` member accordingly before calling `task_thread_info()`. I have pushed a fixup with 3d0f9e3. Do you have a more elegant idea?

**Comment by cnuke** [comment]
@jschlatow thanks for the fixup. From my point of view your solution is fine as it is strictly confined to this function. Another way would be to introduce an arch specific `lx_emul` interface to initialize `task->stack` but I am not sure that this is worth it.

**Comment by jschlatow** [comment]
> @jschlatow thanks for the fixup. From my point of view your solution is fine as it is strictly confined to this function. Another way would be to introduce an arch specific `lx_emul` interface to initialize `task->stack` but I am not sure that this is worth it.

That was my thinking as well.
