### ISSUE TITLE
Add key press/release and relative motion to genode_c_api and dde_linux

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/genode#4543]
- genode_c_api: key-press/release and relative-motion events
- dde_linux: shadow evdev.c and use event C API

**Comment by nfeske** [comment]
I like them!

Your additions to the genode_c_api raise no questions as you closely followed the existing patterns.

Your evdev approach is pretty cool. Admittedly, I was completely unaware of the evbug feature. It may be worth considering your approach for the touchscreen driver of PinePhone instead of emulating the input subsystem in https://github.com/genodelabs/genode-allwinner/blob/master/src/drivers/touch/goodix/input.c.

Regarding the keycode translations, maybe we can find a way in the future to avoid the duplication of the actual numbers, only having a list of Genode enum names, not the numbers. So in the hypothetical event of a number changed in Genode's input/keycodes.h, we won't get inconsistencies. However, as this is a hypothetical scenario, I'd not press too hard for solving this puzzle now. :-)

Please don't hesitate with merging the commits.
