### ISSUE TITLE
gpu/intel: Add support for Intel XE devices

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/genode#4664]
or IGD GEN12 as Intel calls it.

**Comment by nfeske** [comment]
Commit https://github.com/ssumpf/genode/commit/042e6cd2454c61f952f3771a0772731cf9978a64 is massively impressive!

Should https://github.com/ssumpf/genode/commit/62a593362adb471f0bcc44864b28c02f650647f7 be squashed as a fixup?

Does the new driver depend on the platform-driver change, or is the latter only critical for heavy use cases like VBox? I'm asking because I'd merge the GPU-driver changes right now while deferring the commits of issue #4665 until @skalk's review.

**Comment by nfeske** [comment]
The commits entered the master branch. Is this issue ready to be closed?

**Comment by ssumpf** [comment]
Yes
