### ISSUE TITLE
platform_drv: allow PCI bus addressing of devices

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode#4812]
We have a board with two Ethernet controllers (UP-Xtreme) both of these devices have the same `vendor_iid` and `device_id`. 

To have a predictable assignment of the devices to drivers, the policies of the `platform_drv` should support the triplet `bus`, `device` and `function`.

**Comment by chelmuth** [comment]
Would you mind do document the feature in the README?

**Comment by skalk** [comment]
@trimpim: if you need to distinguish in between different devices with same attributes, why don't you use the name of the device as policy item, which in case of PCI devices is the BDF tupel anyway? I would favor that in contrast to re-add XML attributes to the configuration and add additional code to the crucial policy code in the platform driver. Otherwise, please describe your use-case in more detail, why it is not sufficient to use the name.

**Comment by trimpim** [comment]
@skalk I wasn't aware, that the name is actually the BDF for PCI devices. I will change this.

@chelmuth I will update the README.

**Comment by trimpim** [comment]
@skalk sorry I misunderstood you comment at first. This patch is actually not needed.

@chelmuth Therefore I close the issue.
