### ISSUE TITLE
fetchurl start up time is too short for slow wireless networks

### ISSUE THREAD

**Issue by atopia** [genodelabs/genode#5023]
On very slow (wireless) networks, the download fails because the download manager would respawn fetchurl while it was still
initiating the connection.

**Comment by atopia** [comment]
Please disregard the first referenced commit.

**Comment by chelmuth** [comment]
Great that you managed to evade the issues mentioned yesterday. Is this issue related to #5022? Or asked differently: Is the laggy network the referenced WPA3 network? I'm asking because the WPA3 support is still preliminary according to the commit history. Also, 802.11a (5 GHz) has significant more throughput and better ping times than 2.4 GHz in my tests.

| Test                              | 2.4 GHz                                                     | 5 GHz                                                      |
| --------------------------------- | ----------------------------------------------------------- | ---------------------------------------------------------- |
| `wget -O /dev/null <WEB URL>`[^1] | 2,0 MB/s                                                    | 10,2 MB/s                                                  |
| `wget -O /dev/null <LAN URL>`     | 3,0 MB/s                                                    | 13,7 MB/s                                                  |
| `ping -c100 -i 0.2 <LAN IP>`      | rtt ms min/avg/max/mdev<br/>28.067/2627.719/7017.450/1837.350 | rtt ms min/avg/max/mdev<br/>1.789/1233.178/6069.333/1149.476 |

[^1]: DSL uplink is capped to 100 MBit/s by intermediate router.

**Comment by atopia** [comment]
The laggy network is the WPA3 network, but runs mixed WPA2/WPA3 encryption and the startup time issue was initially encountered when configuring the network with `protection="WPA2"` from an existing `wifi` configuration file. The 2.4GHz and 5GHz band have so far been running on the same SSID, but it seems that `wifi_drv` tends to pick up the 2.4 GHz band, probably due to signal strength as is a common problem when running on the same SSID. I will split out the 5 GHz band to a second SSID to fix that part of the problem.

**Comment by atopia** [comment]
@chelmuth you may remove the commit from staging, it does only slightly mitigate the issue in #5024 on my test system but does not solve the underlying issue.
