### ISSUE TITLE
More detailed Github issue/pull labels?

### ISSUE THREAD

**Issue by axiomzzzz** [genodelabs/genode#5298]

**Comment by chelmuth** [comment]
The issue looks like a poll. So, I decided to vote against it above as this is my personal opinion.

**Comment by nfeske** [comment]
Explaining my downvote:

Full-text search for issues already works like a charm. Offering additional labels as search filters is futile because it would require additional discipline from maintainers, accurately labeling issues. Even today with the few labels we have, this is not always done. I don't want to bother any maintainer (myself included) with superficial work like classifying issues. I'm not even speaking of the 5000+ existing issues not labeled, which would evade the filtering via labels.

From my perspective, labels are quite useful to reflect the state and criticality of an issue. In particular, I look out for the "fixed" label while curating the staging branch. The "bug" vs. "feature" labels are useful to prioritize my attention. The labels work for this purpose because they stand out. More labels would merely add noise.
