### ISSUE TITLE
base-hw: busy loop in `Board::Timer::pit_calc_timer_freq()` on StarLite (and potentially Framework)

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/genode#5304]
While debugging boot issues on the StarLite tablet, I identified a busy loop in `Board::Timer::pit_calc_timer_freq()`. The busy loop comes from a supposedly glock-gated PIT as has been identified by the [memtest86+ project](https://github.com/memtest86plus/memtest86plus/issues/40#issuecomment-1098619644).

By skipping `pit_calc_timer_freq()` and setting `ticks_per_ms` to `TIMER_MIN_TICKS_PER_MS`, I was able to successfully boot into run/intel_fb on the StarLite.

This might be related to #5215.

**Comment by jschlatow** [comment]
I'm closing this issue as a duplicate of #5215.

I was able to successfully boot Sculpt on the StarLite. There are a few remaining issues (e.g. missing wifi firmware), yet no other boot issue showed up. Still wondering why the device gets stuck in base-nova, though.

**Comment by alex-ab** [comment]
@jschlatow: I can reproduce the "Bad ELF" with Qemu. Somehow the elf binary which gets generated is not recognized anymore as valid. I have no good explanation, but if you directly use asm volatile("ud2") instead, so removing the while loop and the argument, you get the PT not found exception, which is expected at this stage. 

I am curious, which of the assertion below trigger, maybe because of CPU topology, as your CPU is not common by now in our test parkour.

**Comment by alex-ab** [comment]
I added a debug commit adjusting nova_die

**Comment by jschlatow** [comment]
@alex-ab Thanks for advice. Turns out it gets stuck in `remap_cpu_ids` because `boot->e_core()` ist true.

NOVA reports the following:
```
[ 0] CORE:00:00:0 6:be:0:0 [17] E Intel(R) N200 MWAIT+E+I
[ 3] CORE:00:03:0 6:be:0:0 [17] E Intel(R) N200 MWAIT+E+I
[ 1] CORE:00:01:0 6:be:0:0 [17] E Intel(R) N200 MWAIT+E+I
[ 2] CORE:00:02:0 6:be:0:0 [17] E Intel(R) N200 MWAIT+E+I
```

**Comment by alex-ab** [comment]
@jschlatow: Thanks for your patient and finding the root cause, I opened up a new issue to track the issue.
