### ISSUE TITLE
Support for MNT Pocket (i.MX 8M Plus)

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#5360]

**Comment by cnuke** [comment]
Commit [0bb26f6](https://github.com/cnuke/genode-imx/commit/0bb26f6c4d642ce642b33e3eba4f85b96d5c06b9) adds *MNT Pocket* support to the `stmmac_nic` driver.

I noticed the following messages, which happen after obtaining the IPv4 address:

```
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
[init -> nic] NOHZ tick-stop error: local softirq work is pending, handler #08!!!
```
The messages do nit trigger during operation, i.e., downloading a file from the *MNT Pocket* works fine with around 150 MBit/s without them.

**Comment by cnuke** [comment]
The following commits add initial support (hence the WIP tag on some commits) for the MNT Pocket to Sculpt:

* [875589b](https://github.com/cnuke/genode-imx/commit/875589b51549f1ca743e26955e34412d6d5631e9) adds the `sd_card` image run-tool plugin

* [8017460](https://github.com/cnuke/genode/commit/80174608265d36957400d3c332f1afe29ad8049f) adds initial MNT Pocket support to *sculpt.run* and the `sculpt_manager`

* [b978dba](https://github.com/cnuke/genode/commit/b978dba40312bd830d410397148744a04fde2c19) adds `stmmac_nic` specific options to the *nic*-management (this is just a suggestion on how to tackle the issue)

* [b6c9deb](https://github.com/cnuke/genode-imx/commit/b6c9deb5df32c8b0cd32567c5bc6a26b4cf9bc99) circumvents the dubious errors when starting drivers on Sculpt

* [e43e74a](https://github.com/cnuke/genode-imx/commit/e43e74ac5232afc2f9bc3f9c73ef5c8d16f9a91a) adds the MNT Pocket to the `stmmac_nic` driver. I have not tried to extract the MAC via the eeprom - it currently matches what is set in u-boot.

* [faf0ed7](https://github.com/cnuke/genode-imx/commit/faf0ed7b9ae81311b09ce674929d53f22541c499) adds support for setting the *dtb* ROM name via the config and is necessary for Sculpt (unify all drivers to always request `nic.dtb` would be another option)

* [6a8e886](https://github.com/cnuke/genode-imx/commit/6a8e88687020b52cd114aba1543543681a4a3830) adds the Sculpt configuration for the MNT Pocket


I briefly gave it a spin and noticed the following shortcomings:

* The system feels sluggish (judging by U-Boot the CPUs are clocked at 1200MHz, cranking them up might be an option)

* The display stays black sometimes (transfer timeout, even when the timeout value is raised to 10s), when booting it a second time it usual works
 
* The `imx8mp_qcacld2_wifi` driver does not work properly (it request memory up to the *256 MiB* limit imposed by the `sculpt_manager`) and shows the following messages when trying to update the index file. It is also verbose when parsing the  device-tree due to duplicated entries.
 ```
 AR600: Invalid read length: 5376
 HIFDevIssueRecvPacketBundle, HIFSend Failed status: 14
 ```

* Using the `stmmac_nic` driver to download the index triggers the `page_frag_alloc_align` generated dummy.

**Comment by ssumpf** [comment]
@skalk: [f0570d2](https://github.com/ssumpf/genode-imx/commit/f0570d24591499f665e30b9a7f32af3c40c774ff) implements the screen rotation for the MNT Pocket Reform and uses the device tree in order to identify the platform the driver is running :wink:

**Comment by ssumpf** [comment]
@skalk: [1b10c01](https://github.com/ssumpf/genode-imx/commit/1b10c0187ab7396cf1903642cdea649fe33511ea) is a version with a corrected spelling error.

**Comment by skalk** [comment]
@ssumpf thanks a lot, I've tested it right now. As you already mentioned beforehand there is still a 50% chance the display won't get initialized correctly due to a xfer timeout at DSI. I'll investigate whether CPU quantum can help here, or how to relax that timeout. Nonetheless, I've pushed the current overall MNT pocket Sculpt state to staging.

**Comment by skalk** [comment]
@nfeske could you please review and potentially take commit 4643772 to staging?

**Comment by skalk** [comment]
@nfeske fixup commit 612a13a adds a missing route to the wifi.dtb for Sculpt 24.10 on MNT pocket

**Comment by chelmuth** [comment]
> @nfeske fixup commit [612a13a](https://github.com/genodelabs/genode/commit/612a13a8c88b373f330b3c7171ecbbea9fc68172) adds a missing route to the wifi.dtb for Sculpt 24.10 on MNT pocket

Merged to staging.

**Comment by skalk** [comment]
@chelmuth sorry, when creating an image I realized the pocket is missing in sculpt_image.run as well. Commit 7ceacec solves that.
