### ISSUE TITLE
base-hw: avoid static kernel limitations

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#580]
By now the user must limit the kernels abilities statically through enums like MAX_PDS, MAX_THREADS, MAX_SIGNAL_RECEIVERS, etc. This is because although the kernel objects are created on dynamically donated memory, the metadata of the according ID allocators comes from internal arrays. To get rid of these limitations the metdata costs must be added to the cost of  the syscall that creates the kernel object and the metadata arrays must be replaced by a dynamical structure.

**Comment by m-stein** [comment]
@skalk 
I'm not sure. Do you think that having no limitations in the kernel would be worth the overhead? Otherwise, I'll close the issue.

**Comment by skalk** [comment]
This issue will be fixed by the kernel capabilities soon anyway. There are no MAX_* anyway. The 'id allocator' is now a bitarray that is dimensioned like the whole range of the Kernel::capid_t type.

**Comment by m-stein** [comment]
So, the ``capid`` data and meta data is then part of core-allocated kernel objects?

**Comment by m-stein** [comment]
Sorry misunderstood you. You mean, the ID-allocator will cover all possible IDs..

**Comment by skalk** [comment]
Kernel::capid_t is just an 16-bit unsigned number, so there is no meta-data. It will be part of an Kernel::Object_identity_reference, which aggregates this id, and a reference to a Kernel::Pd and Kernel::Object_identity object. The Object_identity_references are allocated within the kernel part of core, because they might be created during an IPC when capabilities are delegated. Before IPC is started, the kernel has to check whether the corresponding Pd-local allocator has enough entries left to respectively delegate capabilities.
On the other hand, the kernel uses a Pd-local bit-allocator to maintain the free and used capid_t numbers. This allocator has 65536 entries - the whole range of the capid_t type.

**Comment by m-stein** [comment]
Cool. Thank you for the detailed explanation. And the PD-local allocators are filled via the quota of the corresponding PD session, I assume?

**Comment by skalk** [comment]
Oh, next time I have to refresh my browser window before answering, I saw your second post right no, and you are absolutely right.

**Comment by skalk** [comment]
fixed by commit e0815547316362b07f2d32fd67774388fc608b07
