### ISSUE TITLE
os & arm: get rid of board specs in include/platform

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#932]
As far as I can see, most specs in os/include/platform could be (or are already) centralized by the according board-base headers in base/include/platform. Thus I suggest to remove the *_defs headers and use Board_base instead.

**Comment by skalk** [comment]
This issue relates to the general question on how to build and configure drivers that are not bound to a single board, but might have different resource names like interrupts and mmio base addresses, etc.
There are two ways to approach this, either by introducing an equivalent platform_drv for ARM like it exists for x86 and bundle all information here. Alternatively, we could distribute this kind of information in board-specific driver packages of the corresponding driver, and deliver its configuration inside.
Regardless of the way we will go in the midterm future, I do not think that there is a need to unify what is mentioned in this issue right now,  because the mentioned headers are private to the driver (`repos/os/src/drivers/framebuffer/spec/pl11x/pbxa9/`) in the meantime anyway.
@m-stein so do you agree that we can close this issue for now?

**Comment by m-stein** [comment]
Thanks for this explanation! Sounds sensible.
