### ISSUE TITLE
core: enable local session upgrading

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#985]
Previously, upgrading a session locally in core was not needed. However, now at least the RM session uses the local signal service to create a signal context for every pager object and thus might trigger local upgrading. The RAM that would be used for upgrading should be accounted to the client of the corresponding front-end session. In case of RM session the server should claim quota according to the costs of a signal context on every Rm_session::add_client and accumulate it till the next upgrade.

**Comment by skalk** [comment]
I disagree that we need this feature in core. From my point of view it is a design bug that core uses its own signal session to create signal contexts for each thread that needs to be paged. While working on issue #956, which is the result of the current design, I came to the conclusion to use the kernel's signal API directly instead of using core's signal API for the paging notification. The needed kernel's signal context then can be integral part of the Platform_thread instead of core paying for it with its signal session.
Therefore, i would like to close this issue, @m-stein do you agree?

**Comment by m-stein** [comment]
I must admit that I like using the generic signal API. Without that, we would open up terrain for new bugs and raise code complexity as well. At the other hand you're right: It would be nice to let the signal context be part of the RM-client (I would not add it to Platform_thread). Maybe there is a way to combine both goals.

**Comment by skalk** [comment]
I don't think it will be complex to do signaling directly. On the other hand, core does not use the signal library by itself at all. The hint with the Rm_client was good, although I would use the Pager_object instead, to not duplicate the whole rm_session_component.h header again, where the Rm_client class resides in.
I see absolutely no way to use the generic signal library for core's paging code without core paying for each signal. If you see a solution please outline it in more details. Otherwise, I would like to follow my proposal and close this issue.

**Comment by m-stein** [comment]
After a private discussion I agree that we should try using the Kernel API directly at this point. So @skalk you may close this issue by referencing to an alternative or simply rename it.

**Comment by skalk** [comment]
Thanks, It is already referenced above (#956).
